name: Nua
options:
  bundleIdPrefix: com.ykingtech
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.ykingtech.nua
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    CODE_SIGN_STYLE: Automatic
targets:
  Nua:
    type: application
    platform: iOS
    sources:
      - path: Nua
    info:
      path: Nua/Info.plist
    settings:
      base:
        PRODUCT_NAME: Nua
        INFOPLIST_FILE: Nua/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
